package message;

import client.Client;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class Room extends javax.swing.JFrame {

    public DefaultListModel dlmChat;
    public DefaultListModel dlmFolk;
    public String roomName = "";
    public String username = "";
    public File myFile;

    public Room() {
        initComponents();
        dlmChat = new DefaultListModel();
        dlmFolk = new DefaultListModel();
        RoomChat.setModel(dlmChat);
        lFolk.setModel(dlmFolk);
        lblfname.setVisible(false);
    }

    public void updateFolk(ArrayList<String> users) {
        dlmFolk.removeAllElements();
        for (String user : users) {
            dlmFolk.addElement(user);

        }
        lFolk.setModel(dlmFolk);
    }

    public void updateChat(String msg) {

        dlmChat.addElement(msg);
        RoomChat.setModel(dlmChat);
    }

    public static String getExt(String fname) {
        int i = fname.lastIndexOf(".");
        if (i > 0) {
            return fname.substring(i, 1);
        } else {
            return "ext_not_found";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMessageR = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoomChat = new javax.swing.JList<>();
        btnSendR = new javax.swing.JButton();
        lblRoomName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lFolk = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnLeave = new javax.swing.JButton();
        btnChooseF = new javax.swing.JButton();
        lblfname = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setViewportView(RoomChat);

        btnSendR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSendR.setForeground(new java.awt.Color(0, 204, 51));
        btnSendR.setText(">");
        btnSendR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRActionPerformed(evt);
            }
        });

        lblRoomName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRoomName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRoomName.setText("Room Name");

        jScrollPane2.setViewportView(lFolk);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Folk");

        btnLeave.setText("Leave");
        btnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveActionPerformed(evt);
            }
        });

        btnChooseF.setText("Choose File");
        btnChooseF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFActionPerformed(evt);
            }
        });

        lblfname.setText("file");

        btnSend.setText("Send File");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnChooseF)
                                .addGap(18, 18, 18)
                                .addComponent(btnSend))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMessageR, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSendR, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblfname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnLeave)))
                .addGap(0, 58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLeave)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lblRoomName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMessageR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSendR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChooseF)
                            .addComponent(btnSend))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblfname)))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnSendRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRActionPerformed

        String chatmsg = txtMessageR.getText();

        Message msg = new Message(Message.Message_Type.RoomMSG);
        ArrayList<String> elements = new ArrayList<String>();
        elements.add(lblRoomName.getText());
        elements.add(username + ": " + chatmsg);
        msg.content = elements;
        Client.Send(msg);

    }//GEN-LAST:event_btnSendRActionPerformed

    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed

        dlmFolk = new DefaultListModel();
        lFolk.setModel(dlmFolk);
        Message msg = new Message(Message.Message_Type.RoomULeft);
        ArrayList<String> elements = new ArrayList<String>();
        elements.add(username);
        elements.add(lblRoomName.getText());
        msg.content = elements;

        Client.Send(msg);
        this.dispose();
    }//GEN-LAST:event_btnLeaveActionPerformed

    private void btnChooseFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Select a File");
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            myFile = chooser.getSelectedFile();
            lblfname.setText(myFile.getName());
            lblfname.setVisible(true);

        }
    }//GEN-LAST:event_btnChooseFActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed

        if (myFile == null) {
        JOptionPane.showMessageDialog(null, "Please select a file.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                Message msg = new Message(Message.Message_Type.File);
                ArrayList items = new ArrayList<>();
                items.add(roomName);
                items.add(username);
                items.add(myFile.getName());
                byte[] content = Files.readAllBytes(myFile.toPath());
                items.add(content);

                msg.content = items;
                Client.Send(msg);
                myFile = null;
                lblfname.setText("");
                lblfname.setVisible(false);
            } catch (IOException ex) {
                Logger.getLogger(Room.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Room.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Room().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JList<String> RoomChat;
    private javax.swing.JButton btnChooseF;
    public javax.swing.JButton btnLeave;
    private javax.swing.JButton btnSend;
    public javax.swing.JButton btnSendR;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JList<String> lFolk;
    public javax.swing.JLabel lblRoomName;
    private javax.swing.JLabel lblfname;
    private javax.swing.JTextField txtMessageR;
    // End of variables declaration//GEN-END:variables
}
